library(dplyr)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
data <- tbl_df(data)
data2 <- data %>% filter(Date == "1/2/2007" | Date == "2/2/2007") %>% mutate(datetime = paste(Date, Time)) %>% mutate(datetime = strptime(datetime, format = "%d/%m/%Y %H:%M:%S"))
png("plot3.png")
plot(data2$datetime, data2$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(data2$datetime, data2$Sub_metering_2, type = "l", col = "red")
lines(data2$datetime, data2$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = c(2,2,2))
dev.off()