library(dplyr)
url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url, destfile = "consumption.zip")
unzip("consumption.zip")
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
data <- tbl_df(data)
datafilter <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
png(file = "plot1.png")
hist(as.numeric(datafilter$Global_active_power), col = "red", main = "Global Active Power", xlab = "Global Active Power(kilowatts)")
dev.off()